name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Change SSH fingerprint
        run: ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy with rsync
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/webapp/impact-api/
      - name: Restart docker
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/webapp/impact-api/ && docker compose -f compose.yaml -f compose.prod.yaml build --no-cache && docker compose down && docker compose -f compose.yaml -f compose.prod.yaml --env-file .env up --wait"
      - name: Generate JWT Keys
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/webapp/impact-api/ && docker compose exec php sh -c 'set -e ; apt-get install openssl ; php bin/console lexik:jwt:generate-keypair ; setfacl -R -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt; setfacl -dR -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt'"
      - name: Test if website is accessible
        run: curl -s -w "%{http_code}" https://impact.lauradurieux.dev